#FROM apache/airflow:2.7.3-python3.10
FROM apacheairflowimage
#ADD requirements.txt .
#RUN pip install apache-airflow==${AIRFLOW_VERSION} -r requirements.txt
#RUN mkdir -p /opt/airflow/data_lake/raw
#RUN mkdir -p /opt/airflow/data_lake/refined
#RUN mkdir -p /opt/airflow/data_collection